import type { Metadata } from "next";
import Background from "@/components/main/background";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-lvh bg-black justify-center items-center flex flex-col">
      <Header />
      <Background />
      {children}
    </div>
  );
}
